// <auto-generated />
namespace XenDevWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class _202201252154 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202201252154));
        
        string IMigrationMetadata.Id
        {
            get { return "202201251454359_202201252154"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
