//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code changed.
        /// </summary>
        internal static string code_changed {
            get {
                return ResourceManager.GetString("code_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; aready in used..
        /// </summary>
        internal static string code_in_use {
            get {
                return ResourceManager.GetString("code_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete Data?.
        /// </summary>
        internal static string confirm_delete {
            get {
                return ResourceManager.GetString("confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Save Data?.
        /// </summary>
        internal static string confirm_saved {
            get {
                return ResourceManager.GetString("confirm_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Send Estimation Request?.
        /// </summary>
        internal static string confirm_send_estimation_request {
            get {
                return ResourceManager.GetString("confirm_send_estimation_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Submit Data?.
        /// </summary>
        internal static string confirm_submited {
            get {
                return ResourceManager.GetString("confirm_submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Limited.
        /// </summary>
        internal static string co_Ltd {
            get {
                return ResourceManager.GetString("co_Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer accept.
        /// </summary>
        internal static string customer_accept {
            get {
                return ResourceManager.GetString("customer_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer reject.
        /// </summary>
        internal static string customer_reject {
            get {
                return ResourceManager.GetString("customer_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete data. This record is in use or has reference data..
        /// </summary>
        internal static string dataIsUse {
            get {
                return ResourceManager.GetString("dataIsUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string design {
            get {
                return ResourceManager.GetString("design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developer cancel.
        /// </summary>
        internal static string developer_cancel {
            get {
                return ResourceManager.GetString("developer_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email to &apos;{0}&apos; failed..
        /// </summary>
        internal static string email_sended_failed {
            get {
                return ResourceManager.GetString("email_sended_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sended to &apos;{0}&apos;..
        /// </summary>
        internal static string email_sended_success {
            get {
                return ResourceManager.GetString("email_sended_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khun.
        /// </summary>
        internal static string khun {
            get {
                return ResourceManager.GetString("khun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal person.
        /// </summary>
        internal static string legal_person {
            get {
                return ResourceManager.GetString("legal_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting.
        /// </summary>
        internal static string meeting {
            get {
                return ResourceManager.GetString("meeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string menu_admin {
            get {
                return ResourceManager.GetString("menu_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Change Trx.
        /// </summary>
        internal static string menu_application_change_trx {
            get {
                return ResourceManager.GetString("menu_application_change_trx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Hierarchy.
        /// </summary>
        internal static string menu_ApprovalHierarchy {
            get {
                return ResourceManager.GetString("menu_ApprovalHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Request.
        /// </summary>
        internal static string menu_change_request {
            get {
                return ResourceManager.GetString("menu_change_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Master.
        /// </summary>
        internal static string menu_company_master {
            get {
                return ResourceManager.GetString("menu_company_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Staff Assignment.
        /// </summary>
        internal static string menu_create_staff_assignment {
            get {
                return ResourceManager.GetString("menu_create_staff_assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation Lists.
        /// </summary>
        internal static string menu_estimation_list {
            get {
                return ResourceManager.GetString("menu_estimation_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Requirements.
        /// </summary>
        internal static string menu_list_requirements {
            get {
                return ResourceManager.GetString("menu_list_requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Notes.
        /// </summary>
        internal static string menu_meeting_notes {
            get {
                return ResourceManager.GetString("menu_meeting_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string menu_member {
            get {
                return ResourceManager.GetString("menu_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Master.
        /// </summary>
        internal static string menu_problem {
            get {
                return ResourceManager.GetString("menu_problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Master.
        /// </summary>
        internal static string menu_project {
            get {
                return ResourceManager.GetString("menu_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Mandays.
        /// </summary>
        internal static string menu_project_mandays {
            get {
                return ResourceManager.GetString("menu_project_mandays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason Master.
        /// </summary>
        internal static string menu_reject_reason_master {
            get {
                return ResourceManager.GetString("menu_reject_reason_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string menu_staff {
            get {
                return ResourceManager.GetString("menu_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Account.
        /// </summary>
        internal static string menu_staff_account {
            get {
                return ResourceManager.GetString("menu_staff_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Gannt Chart.
        /// </summary>
        internal static string menu_staff_gannt_chart {
            get {
                return ResourceManager.GetString("menu_staff_gannt_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Score.
        /// </summary>
        internal static string menu_staff_score {
            get {
                return ResourceManager.GetString("menu_staff_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Ticket Master.
        /// </summary>
        internal static string menu_staff_ticket {
            get {
                return ResourceManager.GetString("menu_staff_ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Ticket Gannt Chart.
        /// </summary>
        internal static string menu_staff_ticket_gannt_chart {
            get {
                return ResourceManager.GetString("menu_staff_ticket_gannt_chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account.
        /// </summary>
        internal static string menu_user_account {
            get {
                return ResourceManager.GetString("menu_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Approval Hierachy.
        /// </summary>
        internal static string menu_user_approval_hierachy {
            get {
                return ResourceManager.GetString("menu_user_approval_hierachy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image UserAccount.
        /// </summary>
        internal static string menu_user_image {
            get {
                return ResourceManager.GetString("menu_user_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss.
        /// </summary>
        internal static string miss {
            get {
                return ResourceManager.GetString("miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string mr {
            get {
                return ResourceManager.GetString("mr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms.
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        internal static string new_chang {
            get {
                return ResourceManager.GetString("new_chang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data..
        /// </summary>
        internal static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string no_record {
            get {
                return ResourceManager.GetString("no_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership Limited.
        /// </summary>
        internal static string part_Ltd {
            get {
                return ResourceManager.GetString("part_Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Company.
        /// </summary>
        internal static string public_com {
            get {
                return ResourceManager.GetString("public_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Company Limited.
        /// </summary>
        internal static string pub_Co_Ltd {
            get {
                return ResourceManager.GetString("pub_Co_Ltd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement.
        /// </summary>
        internal static string requirement {
            get {
                return ResourceManager.GetString("requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image.
        /// </summary>
        internal static string select_image {
            get {
                return ResourceManager.GetString("select_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option.
        /// </summary>
        internal static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted..
        /// </summary>
        internal static string successfully_deletedRc {
            get {
                return ResourceManager.GetString("successfully_deletedRc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data successfully saved..
        /// </summary>
        internal static string successfully_savedRc {
            get {
                return ResourceManager.GetString("successfully_savedRc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string testing {
            get {
                return ResourceManager.GetString("testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        internal static string upload {
            get {
                return ResourceManager.GetString("upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
